CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    user_id bigint REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    status_id bigint REFERENCES status(id) ON DELETE CASCADE ON UPDATE CASCADE
);