CREATE TABLE orders (
    id SERIAL PRIMARY KEY, 
    CONSTRAINT product_id FOREIGN KEY(id) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE, 
    quantity INTEGER, 
    CONSTRAINT user_id FOREIGN KEY(id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE, 
    CONSTRAINT status_id FOREIGN KEY(id) REFERENCES status(id) ON DELETE CASCADE ON UPDATE CASCADE
    
);